# Generated by Django 5.1.6 on 2025-04-10 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='date_time',
            field=models.DateTimeField(auto_now=True, verbose_name='datetime'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='status',
            field=models.BooleanField(default=True, verbose_name='status'),
        ),
    ]
