# Generated by Django 5.1.6 on 2025-04-10 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_visitor_date_time_visitor_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pass',
            name='created_datetime',
            field=models.DateTimeField(auto_now=True, verbose_name='datetime'),
        ),
    ]
