# Generated by Django 5.1.6 on 2025-04-10 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_pass_created_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='status',
            field=models.CharField(default='In', max_length=3, verbose_name='status'),
        ),
    ]
